'use client';

import { useState, useEffect } from 'react';
import { Sidebar } from '@/components/layout/sidebar';
import { Topbar } from '@/components/layout/topbar';
import { CalendarToolbar } from '@/components/calendar/calendar-toolbar';
import { WeekView } from '@/components/calendar/week-view';
import { ShiftDetailPanel } from '@/components/calendar/shift-detail-panel';
import { EditShiftModal } from '@/components/calendar/edit-shift-modal';
import { NewShiftModal } from '@/components/calendar/new-shift-modal';
import { CopilotPanel } from '@/components/copilot/copilot-panel';
import { useAppStore, useCalendarStore } from '@/store';
import { mockShifts, mockSchedule } from '@/lib/mock-data';
import { loadSetup } from '@/lib/org-store';
import type { Shift } from '@/types';
import { Button } from '@/components/ui/button';
import { Plus, Download } from 'lucide-react';
import { format, parseISO, startOfWeek, endOfWeek, addDays } from 'date-fns';

// ── PDF export helper ────────────────────────────────────────────────────────

function exportSchedulePDF(shifts: Shift[], weekLabel: string, orgName: string) {
  const win = window.open('', '_blank');
  if (!win) { alert('Please allow pop-ups to export PDF.'); return; }

  const rows = shifts.map(s => `
    <tr>
      <td>${s.title ?? s.role?.name ?? 'Shift'}</td>
      <td>${s.date}</td>
      <td>${s.startTime.slice(0,5)} – ${s.endTime.slice(0,5)}</td>
      <td>${s.department?.name ?? '—'}</td>
      <td>${s.location?.name ?? '—'}</td>
      <td>${s.assignments.map(a => a.employee ? `${a.employee.firstName} ${a.employee.lastName}` : '').filter(Boolean).join(', ') || '<span style="color:#f59e0b">Open</span>'}</td>
      <td style="text-align:center">${s.minStaff}</td>
      <td><span style="padding:2px 8px;border-radius:12px;font-size:11px;background:${s.isOpen ? '#fef3c7' : '#d1fae5'};color:${s.isOpen ? '#92400e' : '#065f46'}">${s.isOpen ? 'Open' : 'Scheduled'}</span></td>
    </tr>
  `).join('');

  win.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${orgName} — Schedule ${weekLabel}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 13px; color: #111; padding: 32px; }
    .header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #6366f1; }
    .logo { font-size: 22px; font-weight: 800; color: #6366f1; }
    .meta { font-size: 12px; color: #6b7280; text-align: right; }
    h2 { font-size: 16px; font-weight: 700; margin-bottom: 16px; color: #1f2937; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #f3f4f6; padding: 8px 10px; text-align: left; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: .5px; color: #6b7280; border-bottom: 1px solid #e5e7eb; }
    td { padding: 9px 10px; border-bottom: 1px solid #f3f4f6; vertical-align: middle; }
    tr:hover td { background: #f9fafb; }
    .footer { margin-top: 24px; font-size: 11px; color: #9ca3af; text-align: center; }
    @media print {
      body { padding: 16px; }
      button { display: none !important; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo">⚡ TimeSync</div>
      <div style="font-size:18px;font-weight:700;margin-top:4px">${orgName}</div>
    </div>
    <div class="meta">
      Schedule: <strong>${weekLabel}</strong><br/>
      Generated: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}<br/>
      Total shifts: <strong>${shifts.length}</strong>
    </div>
  </div>

  <h2>Shift Schedule — ${weekLabel}</h2>

  <table>
    <thead>
      <tr>
        <th>Shift</th>
        <th>Date</th>
        <th>Time</th>
        <th>Department</th>
        <th>Location</th>
        <th>Assigned To</th>
        <th style="text-align:center">Min Staff</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="footer">
    Generated by TimeSync Scheduling · ${new Date().toISOString()}
  </div>

  <script>
    window.onload = function() { window.print(); }
  </script>
</body>
</html>`);
  win.document.close();
}

// ── Page component ───────────────────────────────────────────────────────────

export default function SchedulePage() {
  const { setOrg, copilotOpen, setActiveSchedule } = useAppStore();
  const { view, currentDate } = useCalendarStore();

  const [shifts, setShifts]           = useState<Shift[]>(mockShifts);
  const [selectedShift, setSelectedShift] = useState<Shift | null>(null);
  const [modalMode, setModalMode]     = useState<'edit' | 'delete' | null>(null);
  const [showNewShift, setShowNewShift] = useState(false);
  const [newShiftDate, setNewShiftDate] = useState<string | undefined>();
  const [isGenerating, setIsGenerating] = useState(false);
  const [schedule, setSchedule]       = useState(mockSchedule);

  useEffect(() => {
    const setup = loadSetup();
    if (setup) {
      setOrg({
        id: 'local', name: setup.org.name, slug: 'local',
        vertical: setup.org.vertical as any, plan: 'enterprise',
        timezone: setup.org.timezone, locale: 'en-US', currency: 'USD',
        primaryColor: setup.org.primaryColor, settings: {}, featureFlags: {},
        isActive: true, createdAt: new Date().toISOString(),
      });
    }
    setActiveSchedule(mockSchedule.id);
  }, []);

  // Week label for header / export
  const parsedDate = parseISO(currentDate + 'T00:00:00');
  const wStart = startOfWeek(parsedDate, { weekStartsOn: 0 });
  const wEnd   = endOfWeek(parsedDate,   { weekStartsOn: 0 });
  const weekLabel = `${format(wStart, 'MMM d')} – ${format(wEnd, 'MMM d, yyyy')}`;
  const orgName = loadSetup()?.org.name ?? 'TimeSync';

  function handleShiftClick(shift: Shift) {
    setSelectedShift(shift);
    setModalMode(null);
  }

  function handleCreateShift(date?: string) {
    setNewShiftDate(date);
    setShowNewShift(true);
  }

  function handleNewShiftSave(partial: any) {
    const newShift: Shift = {
      id: `shift-${Date.now()}`,
      orgId: 'local',
      ...partial,
      startDatetime: `${partial.date}T${partial.startTime}`,
      endDatetime:   `${partial.date}T${partial.endTime}`,
      durationHours: (() => {
        const [sh, sm] = partial.startTime.split(':').map(Number);
        const [eh, em] = partial.endTime.split(':').map(Number);
        const diff = (eh * 60 + em) - (sh * 60 + sm);
        return diff > 0 ? diff / 60 : (diff + 1440) / 60;
      })(),
      crossesMidnight: partial.shiftType === 'overnight',
      assignments: [],
      metadata: {},
      createdAt: new Date().toISOString(),
    };
    setShifts(prev => [...prev, newShift]);
  }

  function handleSaveShift(updated: Partial<Shift>) {
    setShifts(prev => prev.map(s => s.id === selectedShift?.id ? { ...s, ...updated } : s));
    setSelectedShift(prev => prev ? { ...prev, ...updated } : null);
    setModalMode(null);
  }

  function handleDeleteShift(shiftId: string) {
    setShifts(prev => prev.filter(s => s.id !== shiftId));
    setSelectedShift(null);
    setModalMode(null);
  }

  function handleGenerate() {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setSchedule(s => ({ ...s, status: 'review' }));
    }, 3500);
  }

  function handlePublish() {
    setSchedule(s => ({ ...s, status: 'published' }));
  }

  function handleExportPDF() {
    exportSchedulePDF(shifts, weekLabel, orgName);
  }

  return (
    <div className="flex h-screen overflow-hidden bg-gray-50">
      <Sidebar />

      <div className="flex flex-col flex-1 min-w-0 overflow-hidden">
        <Topbar
          title="Schedule"
          subtitle={`${weekLabel} · ${schedule.status === 'published' ? 'Published' : 'Draft'}`}
          actions={
            <>
              <Button variant="secondary" size="sm" leftIcon={<Download size={13} />} className="text-xs" onClick={handleExportPDF}>
                Export PDF
              </Button>
              <Button variant="primary" size="sm" leftIcon={<Plus size={13} />} className="text-xs" onClick={() => handleCreateShift()}>
                New Shift
              </Button>
            </>
          }
        />

        {isGenerating && (
          <div className="bg-gradient-to-r from-indigo-600 to-purple-600 text-white px-6 py-2.5 flex items-center gap-3">
            <div className="h-4 w-4 rounded-full border-2 border-white/40 border-t-white animate-spin" />
            <p className="text-sm font-medium">AI is generating your schedule — analyzing constraints, optimizing assignments…</p>
          </div>
        )}

        <div className="flex flex-1 min-h-0 overflow-hidden">
          <div className="flex flex-col flex-1 min-w-0 overflow-hidden">
            <CalendarToolbar
              onGenerate={handleGenerate}
              isGenerating={isGenerating}
              scheduleStatus={schedule.status}
              onPublish={handlePublish}
            />
            <div className="flex-1 overflow-hidden">
              {view === 'week' || view === 'department' || view === 'timeline' ? (
                <WeekView
                  shifts={shifts}
                  onShiftClick={handleShiftClick}
                  onCreateShift={handleCreateShift}
                />
              ) : (
                <div className="flex items-center justify-center h-full text-gray-400">
                  <p className="text-sm">{view.charAt(0).toUpperCase() + view.slice(1)} view — coming soon</p>
                </div>
              )}
            </div>
          </div>

          {selectedShift && !copilotOpen && (
            <ShiftDetailPanel
              shift={selectedShift}
              onClose={() => setSelectedShift(null)}
              onEdit={() => setModalMode('edit')}
              onDelete={() => setModalMode('delete')}
            />
          )}

          {copilotOpen && <CopilotPanel />}
        </div>
      </div>

      {/* New Shift modal */}
      {showNewShift && (
        <NewShiftModal
          defaultDate={newShiftDate}
          onSave={handleNewShiftSave}
          onClose={() => setShowNewShift(false)}
        />
      )}

      {/* Edit / Delete modal */}
      {selectedShift && (modalMode === 'edit' || modalMode === 'delete') && (
        <EditShiftModal
          shift={selectedShift}
          mode={modalMode}
          onSave={handleSaveShift}
          onDelete={handleDeleteShift}
          onClose={() => setModalMode(null)}
        />
      )}
    </div>
  );
}
